'area: cli':
  - changed-files:
      - any-glob-to-any-file: ['packages/**']
'area: templates':
  - changed-files:
      - any-glob-to-any-file: ['templates/**', 'Cargo.toml']
'area: docs':
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']
'area: ci':
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'Makefile']
