#![no_std]
//! A minimal two-party escrow — the StellarForge 'escrow' starter template.
//!
//! A payer locks a token amount for a payee. The payer can `release` it to the
//! payee, or `refund` it back to themselves. Demonstrates token transfers, auth,
//! a custom error, persistent storage, and tests. Generated by
//! `sforge init <name> --template escrow`.

use soroban_sdk::{contract, contracterror, contractimpl, contracttype, token, Address, Env};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    InvalidAmount = 3,
    AlreadySettled = 4,
}

#[contracttype]
#[derive(Clone)]
enum DataKey {
    Escrow,
}

#[contracttype]
#[derive(Clone)]
pub struct Escrow {
    pub payer: Address,
    pub payee: Address,
    pub token: Address,
    pub amount: i128,
    pub settled: bool,
}

#[contract]
pub struct EscrowContract;

#[contractimpl]
impl EscrowContract {
    /// Lock `amount` of `token` from `payer`, earmarked for `payee`.
    pub fn init(
        env: Env,
        payer: Address,
        payee: Address,
        token: Address,
        amount: i128,
    ) -> Result<(), Error> {
        payer.require_auth();
        if env.storage().instance().has(&DataKey::Escrow) {
            return Err(Error::AlreadyInitialized);
        }
        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }
        token::Client::new(&env, &token).transfer(&payer, &env.current_contract_address(), &amount);
        env.storage().instance().set(
            &DataKey::Escrow,
            &Escrow {
                payer,
                payee,
                token,
                amount,
                settled: false,
            },
        );
        env.storage().instance().extend_ttl(50_000, 100_000);
        Ok(())
    }

    /// Release the escrow to the payee. Requires the payer's authorization.
    pub fn release(env: Env) -> Result<(), Error> {
        let mut e = Self::load(&env)?;
        e.payer.require_auth();
        if e.settled {
            return Err(Error::AlreadySettled);
        }
        token::Client::new(&env, &e.token).transfer(
            &env.current_contract_address(),
            &e.payee,
            &e.amount,
        );
        e.settled = true;
        env.storage().instance().set(&DataKey::Escrow, &e);
        Ok(())
    }

    /// Refund the escrow to the payer. Requires the payer's authorization.
    pub fn refund(env: Env) -> Result<(), Error> {
        let mut e = Self::load(&env)?;
        e.payer.require_auth();
        if e.settled {
            return Err(Error::AlreadySettled);
        }
        token::Client::new(&env, &e.token).transfer(
            &env.current_contract_address(),
            &e.payer,
            &e.amount,
        );
        e.settled = true;
        env.storage().instance().set(&DataKey::Escrow, &e);
        Ok(())
    }

    pub fn get(env: Env) -> Result<Escrow, Error> {
        Self::load(&env)
    }

    fn load(env: &Env) -> Result<Escrow, Error> {
        env.storage()
            .instance()
            .get(&DataKey::Escrow)
            .ok_or(Error::NotInitialized)
    }
}

#[cfg(test)]
mod test {
    extern crate std;
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::token;

    fn setup() -> (
        Env,
        Address,
        Address,
        Address,
        token::Client<'static>,
        EscrowContractClient<'static>,
    ) {
        let env = Env::default();
        env.mock_all_auths();
        let admin = Address::generate(&env);
        let payer = Address::generate(&env);
        let payee = Address::generate(&env);
        let sac = env.register_stellar_asset_contract_v2(admin);
        let token_id = sac.address();
        let tok = token::Client::new(&env, &token_id);
        token::StellarAssetClient::new(&env, &token_id).mint(&payer, &1_000);
        let id = env.register(EscrowContract, ());
        let client = EscrowContractClient::new(&env, &id);
        // Return token id via the client address indirection.
        (env, payer, payee, token_id, tok, client)
    }

    #[test]
    fn release_pays_payee() {
        let (_env, payer, payee, token_id, tok, client) = setup();
        client.init(&payer, &payee, &token_id, &500);
        assert_eq!(tok.balance(&payer), 500);
        client.release();
        assert_eq!(tok.balance(&payee), 500);
        assert!(client.get().settled);
    }

    #[test]
    fn refund_returns_payer() {
        let (_env, payer, payee, token_id, tok, client) = setup();
        client.init(&payer, &payee, &token_id, &500);
        client.refund();
        assert_eq!(tok.balance(&payer), 1_000);
    }

    #[test]
    fn cannot_double_settle() {
        let (_env, payer, payee, token_id, _tok, client) = setup();
        client.init(&payer, &payee, &token_id, &500);
        client.release();
        assert_eq!(client.try_release(), Err(Ok(Error::AlreadySettled)));
    }

    #[test]
    fn rejects_zero_amount() {
        let (_env, payer, payee, token_id, _tok, client) = setup();
        assert_eq!(
            client.try_init(&payer, &payee, &token_id, &0),
            Err(Ok(Error::InvalidAmount))
        );
    }
}
