#![no_std]
//! A minimal Soroban counter — the simplest StellarForge starter template.
//!
//! Demonstrates instance storage, an authenticated mutation, an event, and a
//! unit test. Generated by `sforge init <name> --template counter`.

use soroban_sdk::{contract, contractimpl, contracttype, symbol_short, Address, Env};

#[contracttype]
enum DataKey {
    Count,
}

#[contract]
pub struct Counter;

#[contractimpl]
impl Counter {
    /// Increment the counter by one and return the new value.
    /// Requires `caller` authorization so the action is attributable.
    pub fn increment(env: Env, caller: Address) -> u32 {
        caller.require_auth();
        let mut count: u32 = env.storage().instance().get(&DataKey::Count).unwrap_or(0);
        count += 1;
        env.storage().instance().set(&DataKey::Count, &count);
        env.storage().instance().extend_ttl(50_000, 100_000);
        env.events()
            .publish((symbol_short!("increment"), caller), count);
        count
    }

    /// Read the current counter value.
    pub fn get(env: Env) -> u32 {
        env.storage().instance().get(&DataKey::Count).unwrap_or(0)
    }
}

#[cfg(test)]
mod test {
    extern crate std;
    use super::*;
    use soroban_sdk::testutils::Address as _;

    #[test]
    fn increments() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register(Counter, ());
        let client = CounterClient::new(&env, &id);
        let caller = Address::generate(&env);

        assert_eq!(client.get(), 0);
        assert_eq!(client.increment(&caller), 1);
        assert_eq!(client.increment(&caller), 2);
        assert_eq!(client.get(), 2);
    }
}
